[package]
name = "callbacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-console = "0.2.1"
js-sys = "0.3.56"
wasm-bindgen = "0.2.79"
yew = "0.19.3"
