[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.web-sys]
features = [
    "console",
    "HtmlElement",
    "MouseEvent",
    "DomRect",
]
